### ISSUE TITLE
Support for ARMv7?

### ISSUE THREAD

**Issue by yuzamei2854** [SkyD666/Rays-Android#20]
Hello, your project seems to be very cool, I wanted to test it on my device, but unfortunately this application does not support the ARMv7 architecture, is there any reason or limitation for this?

**Comment by SkyD666** [comment]
See here: https://github.com/SkyD666/Rays-Android/actions/runs/8581789803

**Comment by yuzamei2854** [comment]
Hey, your app works great, thanks, I noticed that it crashes when the Android file selection app is disabled, but that's not a problem, I hope good things for you and your project. :)

**Comment by SkyD666** [comment]
Please tell me who to disable the android file selection app, so I can test it.

**Comment by yuzamei2854** [comment]
> Please tell me who to disable the android file selection app, so I can test it.

Uh, my custom ROM has this option, I feel like it wasn't supposed to exist, to test it you would need to disable the Android application "com.android.documentsui" somehow, but I don't recommend doing that, also as said, no one would have it disabled.

If you like, I can provide my crash log: https://katb.in/idicelizefe

A possible solution would be to be able to select a folder with another file manager, but again, this is not necessary, the application works perfectly, and I shouldn't have disabled the Android's file selection app in the first place.

**Comment by SkyD666** [comment]
![Screenshot_20240408_103324_com.skyd.rays.jpg](https://github.com/SkyD666/Rays-Android/assets/32453770/1b0774c4-6d5b-4cfa-adbc-a6af195e0b86)

maybe you can try this
Settings - Data - Image source

**Comment by SkyD666** [comment]
> > Please tell me who to disable the android file selection app, so I can test it.
> 
> Uh, my custom ROM has this option, I feel like it wasn't supposed to exist, to test it you would need to disable the Android application "com.android.documentsui" somehow, but I don't recommend doing that, also as said, no one would have it disabled.
> 
> If you like, I can provide my crash log: https://katb.in/idicelizefe
> 
> A possible solution would be to be able to select a folder with another file manager, but again, this is not necessary, the application works perfectly, and I shouldn't have disabled the Android's file selection app in the first place.

Catched the exception: https://github.com/SkyD666/Rays-Android/commit/a45e2d930cb16ccfd9132cc510ebf718cba42ae6
