### ISSUE TITLE
关于方便表情导入与使用的一些想法

### ISSUE THREAD

**Issue by yizhimengxin2233** [SkyD666/Rays-Android#5]
1.可以添加一个**批量导入**功能，**选择文件夹**后导入该文件夹下所有符合拓展名要求的文件，然后弹出一个列表让用户一个一个修改，或者一键ai识别啥的（_主要某些机型开个documentui都能卡半天_）

2.添加**类似于分类**的功能，鉴于已经有tag功能了，所以可以在设置里让用户添加一些**常驻tag**,在每一张导入的表情的tag栏都能选择而不需要手动输入，可以加一个滑动栏（_就类似于旧版b站的那个玩意反正我也不太清楚xd_），主页从左往右滑就能打开，**快速选择**一些tag下的表情

3.添加对**动图**的支持，gif肯定是要适配的(_或许已经很适配了但是我不知道_)，或许能内置一个ffmpeg啥的解决mp4或者webm转gif的问题

4.果然还是有一个**悬浮窗**能在任何应用内快速寻找才会更舒服吧（

（以上建议均未考虑开发难度）
（discord没绑手机号用不了所以还是issues舒服）

**Comment by yizhimengxin2233** [comment]
关于4一个想法
利用无障碍权限识别到用户焦点是否在输入框上，如果有就通过悬浮窗显示面板
隔壁raca可能也能用这个方式

**Comment by SkyD666** [comment]
内置ffmpeg的话，apk体积可能又会增大好几MB

**Comment by yizhimengxin2233** [comment]
> 

这个弄一个常驻通知就行了吧

**Comment by yizhimengxin2233** [comment]
> 内置ffmpeg的话，apk体积可能又会增大好几MB

让永恒自行下载然后放到指定目录也行其实

**Comment by yizhimengxin2233** [comment]
> 目前支持gif，不过ocr只支持识别第一帧，ai分类还不支持gif

其实gif基本上都没什么文字信息的xd

**Comment by SkyD666** [comment]
这个版本支持多选分享 / 删除，支持在添加时，选择图片页面多选表情包

[app_release_github_1.4-beta02.zip](https://github.com/SkyD666/Rays-Android/files/11990284/app_release_github_1.4-beta02.zip)
